// Core data model for the Excel -> numbered Word sections pipeline.
//
// The product is a SECTION TREE, not a flat table. Everything downstream of the
// parser (mapper -> numbering -> renderers -> clipboard output) is built around
// the Section / Subsection / Body shapes below.

/** A top-level numbered section, e.g. `6 FRUIT`. */
export interface Section {
  /** Dotted number, generated by the numbering walk, e.g. "6". */
  number: string;
  /** Section title, e.g. "FRUIT". */
  title: string;
  children: Subsection[];
  /**
   * Optional body rendered directly under the section heading. Used by the
   * header-aware transpose layout (one row -> one section, fields as a table);
   * the A/B/C/D convention leaves this unset and puts bodies on subsections.
   */
  body?: Body;
}

/** A numbered subsection, e.g. `6.1 Fruit Description`. */
export interface Subsection {
  /** Dotted number, generated by the numbering walk, e.g. "6.1". */
  number: string;
  /** Subsection title, e.g. "Fruit Description". */
  title: string;
  body: Body;
}

/** The renderable content of a subsection. Discriminated by `type`. */
export type Body =
  | { type: "text"; content: string }
  | { type: "bullets"; items: string[] }
  | { type: "table"; rows: string[][] };

// ---------------------------------------------------------------------------
// Raw clipboard grid -- the output of today's parser, before any mapping.
//
// A Grid is an array of rows; each row is an array of cell values keyed by
// column position (A, B, C, D, ...). Blank cells are preserved as "" so column
// positions stay aligned for the future A/B/C/D convention mapper.
// ---------------------------------------------------------------------------

export type Cell = string | number | boolean | null;
export type Row = Cell[];
export type Grid = Row[];
